/** Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. **/

#include <stdio.h>

int main() {
	int fib0 = 0, fib1 = 1;
	for (int i = 2; i <= 10; i++) {
		int tmp = fib0;
      	fib0 = fib1;
      	fib1 = tmp + fib1;
   		printf("%d\n", fib1);
   }
	return 0;
}